[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'alvan/vim-closetag'

[[plugins]]
repo = 'jparise/vim-graphql'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'uiiaoo/java-syntax.vim'

[[plugins]]
repo = 'posva/vim-vue'

